# -*- coding: utf-8 -*-
"""stock_Portfolio_Tracker .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIe3_qHp1iu7KvGIXqXvspXScpetbb5Y
"""

pip install yfinance pandas

import yfinance as yf
import pandas as pd

class StockPortfolio:
    def __init__(self):
        self.portfolio = {}

    def add_stock(self, symbol, quantity):
        if symbol in self.portfolio:
            self.portfolio[symbol] += quantity
        else:
            self.portfolio[symbol] = quantity

    def remove_stock(self, symbol, quantity):
        if symbol in self.portfolio:
            if self.portfolio[symbol] >= quantity:
                self.portfolio[symbol] -= quantity
                if self.portfolio[symbol] == 0:
                    del self.portfolio[symbol]
            else:
                print("Error: Not enough shares to remove.")
        else:
            print("Error: Stock not found in portfolio.")

    def track_performance(self):
        total_investment = 0
        current_value = 0

        for symbol, quantity in self.portfolio.items():
            stock = yf.Ticker(symbol)
            current_price = stock.history(period="1d")["Close"].iloc[-1]
            total_investment += current_price * quantity
            current_value += current_price * quantity
            print(f"{symbol}: Quantity: {quantity}, Current Price: ${current_price:.2f}")

        print(f"Total Investment: ${total_investment:.2f}")
        print(f"Current Value: ${current_value:.2f}")
        print(f"Profit/Loss: ${current_value - total_investment:.2f}")

# Example usage:
portfolio = StockPortfolio()
portfolio.add_stock("AAPL", 5)
portfolio.add_stock("GOOGL", 2)
portfolio.add_stock("MSFT", 3)
portfolio.track_performance()

portfolio.remove_stock("AAPL", 2)
portfolio.track_performance()