# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fv1sEJSqs5cy8TUoHHELCw8EBarywQg5
"""

!pip install nltk
import nltk
nltk.download('punkt')

import random
from nltk.tokenize import word_tokenize
import nltk
from IPython.display import display
import ipywidgets as widgets

# Ensure the punkt tokenizer is available
nltk.download('punkt')

# Define a list of greetings and responses
GREETINGS_INPUT = ("hello", "hi", "greetings", "sup", "what's up", "hey")
GREETINGS_RESPONSE = ["Hello!", "Hi there!", "Hey!", "Hi!", "Nice to meet you!"]

# Define a list of goodbye inputs and responses
GOODBYE_INPUT = ("bye", "goodbye", "see you later", "see ya")
GOODBYE_RESPONSE = ["Goodbye!", "See you later!", "Bye!", "Have a great day!"]

# Define a function to respond to user's greetings
def respond_to_greeting(greeting):
    return random.choice(GREETINGS_RESPONSE)

# Define a function to respond to user's goodbye messages
def respond_to_goodbye(goodbye):
    return random.choice(GOODBYE_RESPONSE)

# Define a function to handle user input
def respond_to_input(user_input):
    # Tokenize the user input
    words = word_tokenize(user_input)

    # Check for greetings
    for word in words:
        if word.lower() in GREETINGS_INPUT:
            return respond_to_greeting(word.lower())

    # Check for goodbyes
    for word in words:
        if word.lower() in GOODBYE_INPUT:
            return respond_to_goodbye(word.lower())

    # Default response if no match is found
    return "I'm sorry, I didn't understand that."

# Function to handle the interaction
def on_button_click(b):
    user_input = input_box.value
    if user_input.lower() in GOODBYE_INPUT:
        response = respond_to_goodbye(user_input)
        output_box.value = response
    else:
        response = respond_to_input(user_input)
        output_box.value = response

# Create input and output widgets
input_box = widgets.Text(
    value='',
    placeholder='Type something',
    description='You:',
    disabled=False
)
output_box = widgets.Textarea(
    value='',
    placeholder='Bot response',
    description='Bot:',
    disabled=True
)
button = widgets.Button(description="Send")
button.on_click(on_button_click)

# Display the widgets
display(input_box, button, output_box)